package io.windfall.anticheat.core.check;

public enum CompatFlag {
    VERSION_LEGACY,
    VERSION_COMBAT,
    VERSION_FLAT,
    VERSION_WORLD,
    VERSION_MODERN,
    VERSION_LATEST,
    ENTITY_ID_SENSITIVE,
    LAG_COMPENSATED,
    PURPUR_KB_DEPENDENT,
    VIAVERSION_SENSITIVE,
    GEYSEIR_SENSITIVE,
    DISABLE_ON_MISMATCH,
    RELAX_ON_MISMATCH
}
